- name: Ensure configuration and script directories
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    owner: root
    group: root
    mode: 0755
#    recurse: yes
    state: directory
  with_items:
    - etc
    - etc/httpproxy
    - etc/httpproxy/vhost.d
    - usr/httpproxy
    - usr/httpproxy/bin
    
- name: Ensure write access for docker group
  file:
    path: "{{ docker_ctx }}/{{item}}"
    mode: 0775
    group: docker
    recurse: yes
    state: directory
  with_items:
    - etc/httpproxy/vhost.d

- name: Install maintenance scripts
  template:
    src: "bin/{{ item }}"
    dest: "{{ docker_ctx }}/usr/httpproxy/bin/{{ item }}"
    mode: 0755
  with_items:
    - start.sh
    - stop.sh
    - restart.sh
    
- name: Install "docker-compose.yml" 
  template:
    src: etc/docker-compose.yml
    dest: "{{ docker_ctx | default('/docker') }}/etc/httpproxy/docker-compose.yml"
    owner: root
    group: root
    mode: 0644

- name: Install "application.cfg" 
  template:
    src: etc/application.cfg
    dest: "{{ docker_ctx }}/etc/httpproxy/application.cfg"
    mode: 0644

# https://www.haproxy.com/blog/haproxy-ssl-termination/
