- name: Ensure configuration and script directories
  file:
    path: "{{ docker_ctx }}/{{item}}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - etc
    - etc/httpproxy
    - etc/httpproxy/conf.d
    - etc/httpproxy/html
    - usr/httpproxy
    - usr/httpproxy/bin
    
- name: Ensure write access for docker group
  file:
    path: "{{ docker_ctx }}/{{item}}"
    mode: 0775
    group: docker
    recurse: yes
    state: directory
  with_items:
    - etc/httpproxy/conf.d
    - etc/httpproxy/html

- name: Install "docker-compose.yml" 
  template:
    src: etc/docker-compose.yml
    dest: "{{ docker_ctx | default('/docker') }}/etc/httpproxy/docker-compose.yml"
    owner: root
    group: root
    mode: 0644

- name: Install "application.cfg" 
  template:
    src: etc/application.cfg
    dest: "{{ docker_ctx }}/etc/httpproxy/application.cfg"
    mode: 0644

- name: Install "default.conf" 
  copy:
    src: default.conf
    dest: "{{ docker_ctx }}/etc/httpproxy/conf.d/default.conf"
    group: docker
    mode: 0644    

- name: Clean up old HTML files
  shell: "/bin/rm -rf {{ docker_ctx }}/etc/httpproxy/html/*"
    
- name: Install HTML files (from templates)
  template:
    src: "etc/html/{{ item }}"
    dest: "{{ docker_ctx }}/etc/httpproxy/html/{{ item }}"
    group: docker
    mode: 0664
  with_items:
    - index.html

- name: Install HTML files
  copy:
    src: "etc/html/{{ item }}"
    dest: "{{ docker_ctx }}/etc/httpproxy/html/{{ item }}"
    group: docker
    mode: 0664
  with_items:
    - sbdi-logo.png

- name: Install maintenance scripts
  template:
    src: "bin/{{ item }}"
    dest: "{{ docker_ctx }}/usr/httpproxy/bin/{{ item }}"
    mode: 0755
  with_items:
    - start.sh
    - stop.sh
    - restart.sh
    
    
# https://www.haproxy.com/blog/haproxy-ssl-termination/
