- name: Ensure configuration and script directories
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    owner: root
    group: root
    mode: 0750
    recurse: yes
    state: directory
  with_items:
    - etc
    - etc/httpproxy
    
- name: Install "docker-compose.yml" 
  template:
    src: etc/docker-compose.yml
    dest: "{{ docker_ctx | default('/docker') }}/etc/httpproxy/docker-compose.yml"
    owner: root
    group: root
    mode: 0644

# TODO: Start and stop scripts?

# https://www.haproxy.com/blog/haproxy-ssl-termination/
