version: '3.7'

networks:
  {{ frontend_network }}:
    external: true

services:
{% for node_number in cassandra_node_numbers  %}
  cassandra-{{ node_number }}:
    image: bioatlas/ala-cassandra:v0.5
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints: [node.labels.deployment_host == cassandra-{{ node_number }}]
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-{{ node_number }}
      - CASSANDRA_LISTEN_ADDRESS=cassandra-{{ node_number }}
{% if node_number > 1 -%}
      - CASSANDRA_SEEDS=cassandra-1
{%- endif %}
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=8g
      - HEAP_NEWSIZE=1600m
    volumes:
      - data_cassandra{{ node_number }}:/var/lib/cassandra
    entrypoint: /bin/bash -c "cp /tmp/cassandra.yaml /etc/cassandra/cassandra.yaml && cp /tmp/cassandra-env.sh /etc/cassandra/cassandra-env.sh && /entrypoint-wrap.sh"
    networks:
      - {{ frontend_network }}
    restart: always
    
{% endfor %}
volumes:
{% for node_number in cassandra_node_numbers %}  
  data_cassandra{{ node_number }} :
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/docker_local/var/volumes/cassandra/data_cassandra{{ node_number }}"
      
{% endfor %}      
