---
# tasks file for solrcloud on local docker storage
- name: Ensure configuration and script directories
  file:
    path: "{{ docker_ctx | default('/docker') }}_local/{{item}}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - var
    - var/volumes
    - var/volumes/solrcloud_test
  tags:
    - app_directory

- name: Ensure write access for docker group
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    mode: 0775
    group: docker
    recurse: yes
    state: directory
  with_items:
    - var/volumes/solrcloud_test
  tags:
    - write_access
