# Common varibles:

ansible_connection: ssh  
  
host_name: "{{deployment_prefix}}-{{ inventory_hostname }}"
host_fqdn: "{{host_name}}.{{ domain }}"
ansible_host: "{{deployment_prefix}}-{{  inventory_hostname }}.{{ domain }}"

common_ip_part: "{{ private_subnet | regex_replace('0\\/.+$', '') }}"
host_ip: "{{common_ip_part}}{{ hostvars[inventory_hostname]['nbr'] }}"


# MTU 9000 not poosible (yet) on MicroStac
internal_network_mtu: 1000 

server_image: ubuntu-20.40-server-cloudimg-amd64

root_disk_free_warning: 10%
root_disk_free_critical: 5%

docker_services:
  uat:
    osticket:
      role: submodules/docker-osticket/ansible/roles/osticket
      has_env: true
      httpproxy: true
    httpproxy:
      role: httpproxy
  prod:
    httpproxy:
      role: httpproxy
    
