

docker_applications:
  osticket:
    role: submodules/docker-osticket/ansible/roles/osticket
    config:
      osticket_version: 1.15.4.2
      test_param: "test param specific value"
  emailserver:
    role: roles/docker_apps/emailserver
    config:
      test_param: "test param specific value"
  wordpress:
    role: roles/docker_apps/wordpress
    config:
      test_param: "test param specific value"
  portainer:
    role: portainer
    config:
      test_param: "test param specific value"
  species:
    role: roles/docker_apps/species
    config:
      test_param: "test param specific value"
  spatial:
    role: roles/docker_apps/spatial
    config:
      test_param: "test param specific value"
  regions:
    role: roles/docker_apps/regions
    config:
      test_param: "test param specific value"
  collectory:
    role: roles/docker_apps/collectory
    config:
      test_param: "test param specific value"
  nameindex:
    role: roles/docker_apps/nameindex
    config:
      test_param: "test param specific value"
  biocachebackend:
    role: roles/docker_apps/biocachebackend
    config:
      test_param: "test param specific value"
  loggerservice:
    role: roles/docker_apps/loggerservice
    config:
      test_param: "test param specific value"
  specieslists:
    role: specieslists
    config:
      test_param: "test param specific value"
  apiservice:
    role: roles/docker_apps/apiservice
    config:
      test_param: "test param specific value"
  sds:
    role: roles/docker_apps/sds
    config:
      test_param: "test param specific value"
  dashboard:
    role: dashboard
    config:
      test_param: "test param specific value"
  imageservice:
    role: roles/docker_apps/imageservice
    config:
      test_param: "test param specific value"
  solrcloud:
    role: roles/docker_apps/solrcloud
    config:
      test_param: "test param specific value"
  cassandra:
    role: roles/docker_apps/cassandra
    config:
      test_param: "test param specific value"
  biocache:
    role: roles/docker_apps/biocache
    config:
      test_param: "test param specific value"
  mirroreum:
    role: mirroreum
    config:
      test_param: "test param specific value"
  authentication:
    role: roles/docker_apps/authentication
    config:
      test_param: "test param specific value"

# General deployment options:
  
# Will the services run in a swarm or just under the Docker deamon?
swarm_deployment: yes

# Will we run each service by itself?
# (i.e. without interdependencies, http proxy, CAS a.s.o.)
# TODO: Think this option through...
standalone_deployment: no


# Will we expose internal volumes?
development_deployment: no     


