

docker_applications:
  osticket:
    role: submodules/docker-osticket/ansible/roles/osticket
    config:
      osticket_version: 1.15.4.2
      test_param: "test param specific value"
  emailserver:
    role: roles/docker_apps/emailserver
    config:
      test_param: "test param specific value"
  wordpress:
    role: roles/docker_apps/wordpress
    config:
      test_param: "test param specific value"
  portainer:
    role: portainer
    config:
      test_param: "test param specific value"
  species:
    role: species
    config:
      test_param: "test param specific value"
  spatial:
    role: spatial
    config:
      test_param: "test param specific value"
  regions:
    role: regions
    config:
      test_param: "test param specific value"
  collectory:
    role: collectory
    config:
      test_param: "test param specific value"
  nameindex:
    role: nameindex
    config:
      test_param: "test param specific value"
  biocachebackend:
    role: biocachebackend
    config:
      test_param: "test param specific value"
  loggerservice:
    role: loggerservice
    config:
      test_param: "test param specific value"
  specieslists:
    role: specieslists
    config:
      test_param: "test param specific value"
  apiservice:
    role: apiservice
    config:
      test_param: "test param specific value"
  sds:
    role: sds
    config:
      test_param: "test param specific value"
  dashboard:
    role: dashboard
    config:
      test_param: "test param specific value"
  imageservice:
    role: imageservice
    config:
      test_param: "test param specific value"
  solrcloud:
    role: solrcloud
    config:
      test_param: "test param specific value"
  cassandra:
    role: cassandra
    config:
      test_param: "test param specific value"
  biocache:
    role: biocache
    config:
      test_param: "test param specific value"
  mirroreum:
    role: mirroreum
    config:
      test_param: "test param specific value"
  authentication:
    role: authentication
    config:
      test_param: "test param specific value"

# General deployment options:
  
# Will the services run in a swarm or jus under the Docker deamon?
swarm_deployment: yes

# Will we run each service by itself?
# (i.e. without interdependencies, http proxy, CAS a.s.o.)
# TOOO: Think this option through...
standalone_deployment: no


# Will we expose internal volumes?
development_deployment: no     


