

docker_applications:
  osticket:
    role: submodules/docker-osticket/ansible/roles/osticket
    httpproxy: true
    config:
      osticket_version: 1.15.4.2
      test_param: "test param specific value"
  portainer:
    role: portainer
    httpproxy: true
    config:
      test_param: "test param specific value"


# General deployment options:
  
# Will the services run in a swarm or jus under the Docker deamon?
swarm_deployment: yes

# Will we run each service by itself?
# (i.e. without interdependencies, http proxy, CAS a.s.o.)
# TOOO: Think this option through...
standalone_deployment: no


# Will we expose internal volumes?
development_deployment: no     


