---
- name: Ensure NFS utilities are installed.
  apt:
    name:
      - nfs-common
      - nfs-kernel-server
    state: present

- name: Add NFS export to /etc/exports
  lineinfile:
    path: /etc/exports
    line: '/docker_nfs  *(rw,sync,no_subtree_check,no_root_squash)'

- name: Restart NFS server
  service:
    name: nfs-kernel-server
    state: restarted

