- name: Install rsync
  apt:
    pkg: rsync
    
- name: Check if mount point for docker data "/docker" exists
  stat:
    path: "{{ source_mount_point }}"
  register: backup_source_mount_point
    
- name: Ensure mount point for backup snapshots
  file:
    path: "{{ source_mount_point }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  when: backup_source_mount_point.stat.exists == false
    
- name: Ensure "/opt/sbdi/backup/bin" folder
  file: 
    path: /opt/sbdi/backup/bin
    owner: root 
    group: root
    mode: 0755 
    state: directory
    
- name: Install backup snapshot handling scripts
  template:
    src: "bin/{{ item }}"
    dest: "/opt/sbdi/backup/bin/{{ item | split('.') | first }}"
#    dest: "/opt/sbdi/backup/bin/{{ item | regex_replace('^(.+)\\..*$', '\\1' }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - "prepare_source_snapshot.{{ backup_source_type }}"
    - perform_rsync.all
    - "remove_source_snapshot.{{ backup_source_type }}"

- name: Install sudoers file for backupoperator
  copy:
    src: "43-backupoperator"
    dest: /etc/sudoers.d/43-backupoperator
    owner: root
    group: root
    mode: 0110
    
# Backup sources preform rsync via SSH of backup data as root -> backup targets
# Thus make sure bakup targests are known to root user:
  
- name: Remove known_hosts file of root
  file:
    state: absent
    path: ~backupoperator/.ssh/known_hosts

- name: Accept SSH host keys for hostnames
  shell:  "ssh-keyscan -H {{ deployment_prefix }}-{{ item }} >> ~/.ssh/known_hosts"
  with_items: "{{ groups['backup_targets'] }}"

- name: Accept SSH host keys for  fqdns
  shell:  "ssh-keyscan -H {{ deployment_prefix }}-{{ item }}.{{ domain }} >> ~/.ssh/known_hosts"
  with_items: "{{ groups['backup_targets'] }}"   