- name: Add gluster fs repo
  ansible.builtin.apt_repository:
    repo: 'ppa:gluster/glusterfs-10'
    state: present    
- name: Install basic packages
  apt:
    pkg:
    - glusterfs-server
# /etc/fstab holds:    
#    dev/vdb	/mnt	auto	defaults,nofail,x-systemd.requires=cloud-init.service,comment=cloudconfig	0	2
- name: Unmount lvm device
  mount:
    path: /mnt
    src: "{{ lvm_device }}"
    state: absent
- name: Read lvm device information (always use unit when probing)
  parted: "device={{ lvm_device }} unit=MiB"
  register: sdb_info
- name: Remove all partitions from lvm device
  parted:
    device: "{{ lvm_device }}"
    number: "{{ item.num }}"
    state: absent
  with_items:
   - "{{ sdb_info.partitions }}"
- name: Create partition on lvm device
  parted:
    device: "{{ lvm_device }}"
    number: 1
    flags: [ lvm ]
    state: present
- name: Create volume group
  lvg:
      vg: vg_gluster
      pvs: "{{ lvm_device }}1"
      pesize: 16
      force: yes
      state: present
- name: Create logical volume
  lvol:
      vg: vg_gluster
      lv:  lv_gluster
      size: "{{ size }}"
      opts: "--thinpool"
      force: yes