---
galaxy_info:
  author: OSSHelp team
  description: bind9
  company: OSSHelp
  license: GPLv3
  min_ansible_version: 1.2
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
  galaxy_tags:
    - bind9
