version: '3.7'
networks:
  {{ deployment_prefix }}_sbdi_front:
    external: true
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
{% for s_name, s_props in docker_services.items() %}
{% if s_props['httpproxy'] %}
      - /docker/etc/{{s_name}}/proxy.conf:/etc/nginx/conf.d/{{s_name}}.conf
{% endif %}
{% endfor %}
    networks:
      - {{ deployment_prefix }}_sbdi_front
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
