version: '3.7'

networks:
  {{ frontend_network }}:
    external: true

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - {{ docker_ctx }}/etc/httpproxy/vhost.d:/etc/nginx/vhost.d:ro
    networks:
      - {{ frontend_network }}
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

