version: '3.7'

{% if not standalone_deployment %}
networks:
  {{ frontend_network }}:
    external: true
{% endif %}

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
{% if not swarm_deployment %}    
    container_name: nginx-proxy
{% endif %}
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
{% for s_name, s_props in docker_services.items() %}
{% if s_props['httpproxy'] is defined and s_props['httpproxy'] %}
      - /docker/etc/{{s_name}}/proxy.conf:/etc/nginx/conf.d/{{s_name}}.conf
{% endif %}
{% endfor %}
{% if not standalone_deployment %}
    networks:
      - {{ frontend_network }}
{% endif %}
{% if swarm_deployment %}
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
{% endif %}
