version: '3.7'

networks:
  {{ frontend_network }}:
    external: true

services:
  nginx-proxy:
    image: nginx:1-alpine
    ports:
      - "80:80"
    volumes:
      - {{ docker_ctx }}/etc/httpproxy/conf.d:/etc/nginx/conf.d:ro
      - {{ docker_ctx }}/etc/httpproxy/html:/usr/share/nginx/html/:ro
    networks:
      - {{ frontend_network }}
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

