version: '3.7'
networks:
  osticket_uat_default:
    external: true
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /docker/etc/osticket/proxy.conf:/etc/nginx/conf.d/osticket.conf
    networks:
      - osticket_uat_default
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
