- name: Debug
  debug:
    msg: "{{ groups['storage'] | map('regex_replace', '(^.*$)', deployment_prefix+'-\\1') | list }}"
- name: Create a trusted storage pool
  gluster.gluster.gluster_peer:
    state: present
    nodes: "{{ groups['storage'] | map('regex_replace', '(^.*$)', deployment_prefix+'-\\1') | list }}"
   
# - name: Create brick
#   file:
#     path: /export/docker/brick
#     state: directory
#     owner: root
#     group: root
#     mode: 0775

- name: create gluster volume
  gluster.gluster.gluster_volume:
    state: present
    name: docker
    bricks: /export/docker/brick
    rebalance: yes
    cluster: "{{ groups['storage'] | map('regex_replace', '(^.*$)', deployment_prefix+'-\\1') | list }}"
  run_once: true

