version: '3.7'

networks:
  {{ frontend_network }}:
    external: true

configs:
  config_regions:
    file: "${DOCKER_CTX:-/docker}/etc/regions/config/regions-config.properties"
  config_regions_menu-config:
    file: "${DOCKER_CTX:-/docker}/etc/regions/config/menu-config.json"
  config_regions_state-emblems:
    file: "${DOCKER_CTX:-/docker}/etc/regions/config/state-emblems.json"

services:
  regions:
    image: bioatlas/ala-regions:v3.3.5
    environment:
      JAVA_OPTS: -Xmx2g -Xms128m -Xss256k -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom -Dlog4j2.formatMsgNoLookups=true
    env_file: "${DOCKER_CTX:-/docker}/etc/regions/env/.envregions"
    configs:
      - source: config_regions
        target: /data/regions/config/regions-config.properties
      - source: config_regions_menu-config
        target: /data/regions/config/menu-config.json
      - source: config_regions_state-emblems
        target: /data/regions/config/state-emblems.json
    networks:
      - {{ frontend_network }}
