- name: Install and configure Nagios server
  hosts: nagios_servers
  become: true
  tasks:
  - name: SBDI utility scripts
    include_role:
      name: nagiosserver
    vars:
      nagios_server_port: 8088
      
# - name: Configure NRPE Clients for monitoring
#   hosts: gateways:servers:!nagios_servers
#   become: true
#   roles:
#     - monitored_by_nagios

# - name: Configure Nagios Server Monitoring
#   hosts: nagios_servers
#   become: true
#   roles:
#     - nagios_monitoring
