---
# tasks file for loggerservice- name: Ensure configuration and script directories
- name: Ensure configuration and script directories
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - etc
    - etc/loggerservice
    - etc/loggerservice/env
    - etc/loggerservice/config
    - etc/loggerservice/initdb.d
    - usr/loggerservice
    - usr/loggerservice/bin
  tags:
    - app_directory

- name: Ensure write access for docker group
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    mode: 0775
    group: docker
    recurse: yes
    state: directory
  with_items:
    - etc/loggerservice
  tags:
    - write_access

- name: Install "envlogger.template"
  copy:
    src: etc/envlogger.template
    dest: "{{ docker_ctx | default('/docker') }}/etc/loggerservice/env/envlogger.template"
    mode: 0644
  tags:
    - env_template

- name: Copy Database initialization files
  copy:
    src : "{{ item }}"
    dest : "{{ docker_ctx | default('/docker') }}/etc/loggerservice/initdb.d"
    mode: 0644
  with_items:
    - etc/initdb.d/
  tags:
    - db_schema

- name: Install "docker-compose.yml"
  template:
    src: etc/docker-compose.yml
    dest: "{{ docker_ctx | default('/docker') }}/etc/loggerservice/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  tags:
    - docker_compose

- name: Install loggerservice configuration file
  template:
    src: etc/config/logger-config.properties
    dest: "{{ docker_ctx | default('/docker') }}/etc/loggerservice/config/logger-config.properties"
    mode: 0644
  tags:
    - app_config

- name: Install "application.cfg"
  template:
    src: etc/application.cfg
    dest: "{{ docker_ctx | default('/docker') }}/etc/loggerservice/application.cfg"
    mode: 0644
  tags:
    - application_cfg

- name: Install "proxy.conf"
  template:
    src: etc/proxy.conf
    dest: "{{ docker_ctx | default('/docker') }}/etc/loggerservice/proxy.conf"
    mode: 0644
  tags:
    - proxy_conf
