- name: install ha proxy packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - haproxy
- name: configure ha proxy
  template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify:
    - restart haproxy
