ansible_connection: ssh

# TOOO: Is following working and used? 
ansible_ssh_common_args: "-J {{ deployment_prefix }}-{{ groups['gateways'][0] }}.{{ domain }}"
ansible_host: "{{deployment_prefix}}-{{  inventory_hostname }}.{{ domain }}"