# Default (fallback) block device to use for docker storage
# NOTE: If a volume is not specified for a storage host
# an ephimeral disk is assuemd to be present - and will be used.

lvm_device: /dev/vdb

replica_count: 3
