---
# tasks file for mirroreum
- name: Ensure configuration and script directories
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - etc
    - etc/mirroreum
    - etc/mirroreum/env
    - etc/mirroreum/config
    - usr/mirroreum
    - usr/mirroreum/bin
  tags:
    - app_directory

- name: Ensure write access for docker group
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    mode: 0775
    group: docker
    recurse: yes
    state: directory
  with_items:
    - etc/mirroreum
  tags:
    - write_access

- name: Install "envmirroreum.template"
  copy:
    src: etc/envmirroreum.template
    dest: "{{ docker_ctx | default('/docker') }}/etc/mirroreum/env/envmirroreum.template"
    mode: 0644
  tags:
    - env_template

- name: Install "docker-compose.yml"
  template:
    src: etc/docker-compose.yml
    dest: "{{ docker_ctx | default('/docker') }}/etc/mirroreum/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  tags:
    - docker_compose

- name: Install mirroreum configuration file
  template:
    src: etc/config/rserver.conf
    dest: "{{ docker_ctx | default('/docker') }}/etc/mirroreum/config/rserver.conf"
    mode: 0644
  tags:
    - app_config

- name: Install "application.cfg"
  template:
    src: etc/application.cfg
    dest: "{{ docker_ctx | default('/docker') }}/etc/mirroreum/application.cfg"
    mode: 0644
  tags:
    - application_cfg

- name: Install "proxy.conf"
  template:
    src: etc/proxy.conf
    dest: "{{ docker_ctx | default('/docker') }}/etc/mirroreum/proxy.conf"
    mode: 0644
  tags:
    - proxy_conf
