- name: Ensure /opt/sbdi folder
  file: 
    path: /opt/sbdi
    owner: root 
    group: root
    mode: 0755 
    state: directory

- name: Ensure /opt/sbdi/bin folder
  file: 
    path: /opt/sbdi/bin
    owner: root 
    group: root
    mode: 0755 
    state: directory

- name: Copy docker (template) maintenance scripts
  template:
    src: "bin/{{ item }}"
    dest: /opt/sbdi/bin/{{ item }}
    owner: root
    group: root
    mode: 0755
  with_items:
    - list_docker_apps
    - start_docker_app
    - stop_docker_app
    - ensure_docker_host_labels
    - ensure_local_docker_volume
    - ensure_global_docker_volume
  tags:
    - docker_maintenance_scripts
    
- name: Copy docker maintenance scripts
  copy:
    src: "bin/{{ item }}"
    dest: /opt/sbdi/bin/{{ item }}
    owner: root
    group: root
    mode: 0755
  with_items:
    - service_exec
  tags:
    - docker_maintenance_scripts