- name: install nrpe packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - nagios-nrpe-server
#    - nagios-nrpe-plugin
    - monitoring-plugins
  notify:
    - restart nrpe
