- name: "Determine ipsec users"
  set_fact:
    ip_sec_users: "{{ admin_users | dict2items | selectattr('value.ipsec_access', 'equalto', true) | list  }}"

# - name: "Show us the users selected"
#   debug:
#     var: ip_sec_users
  
- name: "Upload ipsec install scrip - if there are ipsec users"
  template:
    src: "vpnsetup.sh"
    dest: /tmp/vpnsetup.sh
    owner: root
    mode: 0755
  when: ip_sec_users | length > 0


- name: "Ensure ipsec server - if there are ipsec users"
  ansible.builtin.shell: "sudo sh /tmp/vpnsetup.sh"
  when: ip_sec_users | length > 0

- name: "Delete ipsec install scrip and its contained secret"
  file:
    state: absent
    path: /tmp/vpnsetup.sh

- name: "Upload ipsec update users scrip - if there are ipsec users"
  template:
    src: "updatevpnusers.sh"
    dest: /tmp/updatevpnusers.sh
    owner: root
    mode: 0755
  when: ip_sec_users | length > 0
  
- name: "Ensure correct ipsec users - if there are ipsec users"
  ansible.builtin.shell: "echo 'y' | sudo sh /tmp/updatevpnusers.sh"
  when: ip_sec_users | length > 0  

- name: "Delete ipsec update users scrip and its contained secrets"
  file:
    state: absent
    path: /tmp/updatevpnusers.sh

# TODO: Check if ipsec is installed for following two steps
    
- name: "Download ipsec uninstall script - if there are no ipsec users"
  get_url:
    url: "https://git.io/vpnuninstall"
    timeout: 30
    dest: /tmp/vpnuninstall.sh
    owner: root
    mode: 0755
  when: ip_sec_users | length == 0

- name: "Uninstall ipsec server - if there are no ipsec users"
  ansible.builtin.shell: "echo 'y' | sudo sh /tmp/vpnuninstall.sh"
  when: ip_sec_users | length == 0


