version: '3.7'

networks:
  {{ frontend_network }}:
    external: true

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
{% for s_name, s_props in docker_services.items() %}
{% if s_props['httpproxy'] is defined and s_props['httpproxy'] %}
      - /docker/etc/{{s_name}}/proxy.conf:/etc/nginx/conf.d/{{s_name}}.conf
{% endif %}
{% endfor %}
    networks:
      - {{ frontend_network }}
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
