---
# tasks file for nameindex
- name: Ensure configuration and script directories
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - etc
    - etc/nameindex
    - usr/nameindex
    - usr/nameindex/bin
  tags:
    - app_directory

- name: Ensure write access for docker group
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    mode: 0775
    group: docker
    recurse: yes
    state: directory
  with_items:
    - etc/nameindex
  tags:
    - write_access

- name: Install "docker-compose.yml"
  template:
    src: etc/docker-compose.yml
    dest: "{{ docker_ctx | default('/docker') }}/etc/nameindex/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  tags:
    - docker_compose

- name: Install "application.cfg"
  template:
    src: etc/application.cfg
    dest: "{{ docker_ctx | default('/docker') }}/etc/nameindex/application.cfg"
    mode: 0644
  tags:
    - application_cfg
