- name: Ensure configuration and script directories
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - etc
    - etc/wordpress
    - etc/wordpress/env
    - usr/wordpress
    - usr/wordpress/bin
    - var/volumes
    - var/volumes/wordpress
    - var/backup
    - var/backup/wordpress

- name: Ensure write access for docker group
  file:
    path: "{{ docker_ctx }}/{{item}}"
    mode: 0775
    group: docker
#    recurse: yes
    state: directory
  with_items:
    - var/volumes/wordpress
    - etc/wordpress
    - var/backup/wordpress
#    - var/backup/wordpress/seed

    
- name: Install "docker-compose.yml" 
  template:
    src: etc/docker-compose.yml
    dest: "{{ docker_ctx | default('/docker') }}/etc/wordpress/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
    
- name: Install environemnt template 
  copy:
    src: etc/envwordpress.template
    dest: "{{ docker_ctx }}/etc/wordpress/env/envwordpress.template"
    mode: 0644
    
- name: Install "application.cfg" 
  template:
    src: etc/application.cfg
    dest: "{{ docker_ctx }}/etc/wordpress/application.cfg"
    mode: 0644

- name: Install "proxy.conf" 
  template:
    src: etc/proxy.conf
    dest: "{{ docker_ctx }}/etc/wordpress/proxy.conf"
    mode: 0644
    
- name: Install maintenance scripts
  template:
    src: "bin/{{ item }}"
    dest: "{{ docker_ctx }}/usr/wordpress/bin/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - backup.sh       
    - restore_backup.sh
    - translate.sh
    
# - name: Install seed backup
#   copy:
#     src: "files/backup/seed/{{ item }}"
#     dest: "{{ docker_ctx }}/var/backup/wordpress/seed/{{ item }}"
#     group: docker
#     mode: 0644
#   with_items:
#     - main-wordpress-db.sql
#     - main-wordpress-files.tgz
#     - docs-wordpress-db.sql
#     - docs-wordpress-files.tgz
#     - tools-wordpress-db.sql
#     - tools-wordpress-files.tgz
