---
- name: Setup backup user for director
  become: true
  hosts: backup_director
  roles:
    - backup_director

- name: Setup backup user for sourec and target 
  become: true
  hosts: backup_targets:backup_sources:docker_swarm:docker
  roles:
    - backup_directed

- name: Setup backup source nodes
  become: true
  hosts: backup_sources
  roles:
    - backup_source

- name: "Take an inventory of volumes in our cloud"
  hosts: localhost
  tasks:
    - name: "Register info about all volumes"
      openstack.cloud.volume_info:
      register: volume_info    

- name: Setup backup target (storage of backups)
  become: true
  hosts: backup_targets
  gather_facts: yes
  tasks:
    - name: "Filter out volume device id if there is a backup volume attached"
      set_fact:
        volume_device_id:  "virtio-{{item.id}}"
      with_items: "{{ hostvars['localhost'].volume_info.volumes }}"
      when: item.name | regex_search("^"+deployment_prefix+"-"+inventory_hostname+"-volume_backup$")
      
    - name: "The volume device id that we are looking for:"
      debug:
        var: volume_device_id
      
    - name: "Set backup_data_device to be an atached volume if there is one attached"
      set_fact:
        backup_data_device:  "/dev/{{ item }}"
      with_items: "{{ ansible_facts.devices }}"
      when: ansible_facts.devices[item].links.ids | select('in', volume_device_id) | list | length > 0

    - name: "Setup backup target node with backup data on {{ backup_data_device }}"
      include_role:
        name: backup_target

- name: "Setup backup docker control node"
  become: true
  hosts: docker_swarm:docker
  roles:
    - backup_docker_control
