---
- name: Add backup operator user on backup director node
  become: true
  hosts: backup_director
  tasks:
    - ansible.builtin.user:
        name: backupoperator
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
      register: backupoperator_data
    - debug: var=backupoperator_data
    # - set_fact:
    #     public_key: "{{ret['ssh_public_key']}}"
    #     cacheable: yes
    # - debug: var=public_key
- name: Add backup operator user on backup source and target nodes
  become: true
  hosts: backup_target
  tasks:
    - debug: var=hostvars[groups['backup_director'][0]]
    - ansible.builtin.user:
        name: backupoperator
    - ansible.posix.authorized_key:
        user: backupoperator
        state: present
        key: "{{hostvars[groups['backup_director'][0]]['backupoperator_data']['ssh_public_key']}}"
