---
- name: Setup backup director node
  become: true
  hosts: backup_director
  roles:
    - backup_director

- name: Setup backup target nodes
  become: true
  hosts: backup_targets
  roles:
    - backup_target
    
- name: Setup backup source nodes
  become: true
  hosts: backup_sources
  roles:
    - backup_source
