#---
#- name: Custom ingress network
#  hosts: docker_swarm
#  tasks:
#  - name: Remove default/existing docker ingress network
#    shell: "echo 'y\r' | docker network rm ingress && sleep 5"

  - name: remove default ingress network
    ansible.builtin.expect:
      command: docker network rm ingress
      responses:
        "[y/N]": "y"

  - name: Create custom docker ingress network
    shell: docker network create --driver overlay --ingress --opt com.docker.network.driver.mtu=1450 ingress
