---
- name: Ensure Security Groups and rules
  hosts: localhost
  roles:
    - security_groups
  tags:
    - security_groups

- name: Ensure Internal Network
  hosts: localhost
  roles:
    - internal_network
  tags:
    - internal_network
    
- name: Ensure Storage Volumes
  hosts: localhost
  roles:
    - storage_volumes
  tags:
    - storage

#
# Compute security groups for all hosts
# and set them as facts
#

- name: Set Gateway security groups
  hosts: gateways
  tasks:
    - set_fact:
        security_groups: ['http_access', 'email_access', 'dns_access', 'default']
  tags:
    - hosts
        
- name: Set Server security groups
  hosts: servers
  tasks:
    - set_fact:
        security_groups: ['default']
  tags:
    - hosts
    
- name: Set IPSEC Server security groups
  hosts: ipsec_servers
  tasks:
    - set_fact:
        security_groups: "{{ security_groups | union(['vpn_access']) }}" 
  tags:
    - hosts
        
- name: List security groups
  hosts: gateways + servers
  tasks:
    - debug:
        var: security_groups
  tags:
    - hosts

    
#
# Deploy all hosts, set internal and external ips, security groups and attach storage 
#

- name: Deploy Hosts
  hosts: localhost
  tasks:
    
    #
    # Internal IPs
    #
    - name: "Ensure fixed (internal) IP ports for servers and gateways"
      openstack.cloud.port:
        state: present
        name: "port_of_{{ deployment_prefix }}-{{ item }}"
        network: "{{ deployment_prefix  }}_sbdi_network"
        fixed_ips:
          - ip_address: "{{ hostvars[item]['common_ip_part'] }}{{ hostvars[item]['nbr'] }}"
      with_items: "{{ groups['gateways'] + groups['servers'] }}"
      tags:
        - hosts
        - hosts_internal_ips
      
    #
    # Deploy Hosts
    #
    # Note! There is a bug: security groups are not addedd if not done twice...
    
    - name: "Ensure that hosts are deployed"
      openstack.cloud.server:
        name: "{{ deployment_prefix }}-{{ item }}"
        state: present
        image: "{{server_image}}"
        flavor: "{{ hostvars[item]['flavor'] }}"
        auto_floating_ip: no
        nics:
          - port-name: "port_of_{{ deployment_prefix }}-{{ item }}"
        key_name: "{{ lookup('env','USER') }}_key"
        security_groups: hostvars[item]['security_groups']
      with_items: "{{ groups['servers'] +  groups['gateways'] }}"
      tags:
        - hosts

    - name: "Repeat to ensure security groups for hosts are correct (Bugg workarround)"
      openstack.cloud.server:
        name: "{{ deployment_prefix }}-{{ item }}"
        state: present
        image: "{{server_image}}"
        flavor: "{{ hostvars[item]['flavor'] }}"
        auto_floating_ip: no
        nics:
          - port-name: "port_of_{{ deployment_prefix }}-{{ item }}"
        key_name: "{{ lookup('env','USER') }}_key"
        security_groups: "{{ hostvars[item]['security_groups'] }}"
      with_items: "{{ groups['servers'] +  groups['gateways'] }}"
      tags:
        - hosts
        
    #
    # Attach storage to hosts
    #
    - name: "Attach gluster data volumes to servers"
      openstack.cloud.server_volume:
        state: present
        server: "{{ deployment_prefix }}-{{ item }}"
        volume: "{{ deployment_prefix }}-{{ item }}-volume_gluster"
        device: "{{ hostvars[item]['data_volume_device'] }}"
      with_items: "{{ groups['servers'] }}"
      when:  hostvars[item]['volume_gluster'] is defined
      tags:
        - hosts
        - hosts_storage
        - hosts_gluster_storage
      
    - name: "Attach backup data volumes to servers"
      openstack.cloud.server_volume:
        state: present
        server: "{{ deployment_prefix }}-{{ item }}"
        volume: "{{ deployment_prefix }}-{{ item }}-volume_backup"
        device: "{{ hostvars[item]['data_volume_device'] }}"
      with_items: "{{ groups['servers'] }}"
      when:  hostvars[item]['volume_backup'] is defined
      tags:
        - hosts
        - hosts_storage
        - hosts_backup_storage

    - name: "Attach local docker data volumes to servers"
      openstack.cloud.server_volume:
        state: present
        server: "{{ deployment_prefix }}-{{ item }}"
        volume: "{{ deployment_prefix }}-{{ item }}-volume_local_docker"
        device: "{{ hostvars[item]['data_volume_device'] }}"
      with_items: "{{ groups['servers'] }}"
      when:  hostvars[item]['volume_local_docker'] is defined 
      tags:
        - hosts
        - hosts_storage
        - hosts_local_storage
      
    #
    # Attach floating ips 
    #
      
    - name: "Ensure external IPs on servers (with floating ip)"
      openstack.cloud.floating_ip:
        state: present
        server: "{{ deployment_prefix }}-{{ item }}"
        network: "{{ external_network }}"
        reuse: yes
        floating_ip_address: "{{  hostvars[item]['floating_ip'] }}"
        nat_destination: "{{ deployment_prefix  }}_sbdi_network"
      with_items: "{{ groups['gateways'] + groups['servers'] }}"
      when: hostvars[item]['floating_ip'] is defined 
      tags:
        - hosts
        - hosts_floating_ips


 
  
    
