---
- name: Deploy Cloud Servers
  hosts: localhost
  vars:
    common_ip_part: "{{ private_subnet | regex_replace('0\\/.+$', '') }}"
  tasks:
    - openstack.cloud.network:
        state: present
        name: "{{ deployment_prefix  }}_sbdi_network"
    - openstack.cloud.subnet:
        state: present
        network_name: "{{ deployment_prefix }}_sbdi_network"
        name: "{{ deployment_prefix }}_sbdi_subnet"
        cidr: "{{ private_subnet }}"
    - openstack.cloud.router:
        state: present
        name: "{{ deployment_prefix  }}_sbdi_router"
        network: external
        interfaces:
          - "{{ deployment_prefix }}_sbdi_subnet"
    - openstack.cloud.port:
        state: present
        name: "port_of_{{ deployment_prefix }}_{{ item }}"
        network: "{{ deployment_prefix  }}_sbdi_network"
        fixed_ips:
          - ip_address: "{{  common_ip_part }}{{ hostvars[item]['nbr'] }}"
      with_items: "{{ groups['gateways'] + groups['servers'] }}"
    - openstack.cloud.server:
        name: "{{ deployment_prefix }}_{{ item }}"
        state: present
        image: "{{server_image}}"
        flavor: "{{ hostvars[item]['flavor'] }}"
        auto_floating_ip: no
        nics:
          - port-name: "port_of_{{ deployment_prefix }}_{{ item }}"
        key_name: "{{ lookup('env','USER') }}_key"
      with_items: "{{ groups['gateways']  + groups['servers'] }}"
    - openstack.cloud.floating_ip:
        state: present
        server: "{{ deployment_prefix }}_{{ item }}"
        network: external
        reuse: yes
        floating_ip_address: "{{  hostvars[item]['floating_ip'] }}"
        nat_destination: "{{ deployment_prefix  }}_sbdi_network"
      with_items: "{{ groups['gateways'] }}"