---
# - name: Fix docker
#   hosts: docker_swarm:docker
#   become: true
#   roles:
#     - docker
    
- name: Setup docker networks
  hosts: manager-1
  tasks:
    - name: Create docker network 'sbdi_front'
      docker_network:
        name: "{{deployment_prefix}}_sbdi_front"
        scope: swarm
        ipam_config:
          - subnet: 10.211.1.0/24
            
- name: Install Docker Appplications
  hosts: manager-1
  vars:
    docker_ctx: "{{  docker_root | default('/docker') }}"
  become: true
  roles:
    - httpproxy
    - role: 'submodules/docker-osticket/ansible/roles/osticket'
  tasks:
    - name: Setup env for Osticket
      copy:
        src: docker/etc/osticket/env/{{ deployment_prefix }}/envosticket
        dest: "{{ docker_ctx }}/etc/osticket/env/.envosticket"
        decrypt: yes
        owner: root
        group: docker
        mode: 0640
        backup: no
    - name: Deploy Osticket
      docker_stack:
        state: present
        name: osticket
        compose:
          - "{{ docker_ctx }}/etc/osticket/docker-compose.yml"
    - name: Deploy Httpproxy
      docker_stack:
        state: present
        name: httpproxy
        compose:
          - "{{ docker_ctx }}/etc/httpproxy/docker-compose.yml"

- name: Setup ha proxy access
  hosts: access-1
  become: true
  roles:
    - haproxy
