---
# Work in progress
# - name: Fix local volumes
#   hosts: docker:docker_swarm
#   become: true
#   tasks:
#     - name: Make sure '/var/lib/docker_volume' is a link to  '/docker/var/lib/<hostname>/volumes'
#       file:
#         src: "/docker/var/lib/{{host_name}}/volumes"
#         dest: "/var/lib/docker_volumes"
#         owner: root
#         group: root
#         mode: 0750
#         state: link

    
# - name: Setup docker networks
#   hosts: swarm_managers[0]
#   tasks:
#     - name: Create docker network 'sbdi_frontend'
#       docker_network:
#         name: "sbdi_frontend"
#         scope: swarm
#         driver: overlay
#         #        internal: yes
#         appends: yes
#         ipam_config:
#           - subnet: 10.211.1.0/24
            
- name: Install Docker Swarm Applications
  hosts: swarm_managers[0]
  vars:
    docker_ctx: "{{ docker_root | default('/docker') }}"
    application_declarations: "{{ docker_applications | dict2items }}"
  become: true
  tasks:

  - name: Deploy applications
    include_role:
      name: "{{ application_declaration.value['role']}}"
    loop: "{{ application_declarations }}"
    loop_control:
      loop_var: application_declaration
    tags:
      - applications

# TODO: Inject config here somehow
# There is a bug in ansible that excludes vars: "{{ application_declaration.value['config'] }}"
# Might work with a vars_from file:
# https://docs.ansible.com/ansible/2.3/include_role_module.html
      

  - name: Setup environment configuration for all applications
    copy:
      src: "docker/etc/{{application_declaration.key}}/{{deployment_prefix}}/"
      dest: "{{ docker_ctx }}/etc/{{application_declaration.key}}/env/"
      decrypt: true
      owner: root
      group: docker
      mode: 0640
    loop: "{{ application_declarations }}"
    loop_control:
      loop_var: application_declaration
    tags:
      - configuration

      
- name: Deploy HTTP proxy
  hosts: swarm_managers[0]
  vars:
    docker_ctx: "{{ docker_root | default('/docker') }}"
    application_declarations: "{{ docker_applications | dict2items }}"
  become: true
  tags:
    - httpproxy
  roles:
    - httpproxy


- name: Setup HA proxy access
  hosts: gateways
  become: true
  tags:
    - haproxy
  roles:
    - haproxy


