# The docker storage playbook will setup shared Gluster storage on all storage_clients provided at the /docker mointpoint.
# The Gluster volume 'docker' is provided by the storage servers
# There should be three (3) storage servers to enable safe reboot of any of these servers during maintenance
# The Gluster volume is backed by a thinly provissioned logical volume (lvm).
# Thus Gluster volume snapshots may be used to backup all data in all docker containers instantly.


---
- name: Setup storage for Docker data on all storage nodes 
  hosts: storage
  become: true
  roles:
  - role: docker_storage
- name: Setup Gluster Server on all storage nodes 
  hosts: storage
  become: true
  roles:
  - role: gluster_server
- name: Setup GlusterFS Volume for Docker data 
  hosts: "{{ groups['storage'][0] }}"
  become: true
  roles:
  - role: docker_gluster_volume
- name: Setup Gluster Client on all storage clients that are not backends 
  hosts: storage_clients:!storage
  become: true
  roles:
  - role: gluster_client
- name: Ensure Docker data access on all storage clients
  hosts: storage_clients
  become: true
  roles:
  - role: docker_data_access    


# http://manpages.ubuntu.com/manpages/xenial/man7/lvmthin.7.html
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/logical_volume_manager_administration/thinly_provisioned_volume_creation
# https://www.theurbanpenguin.com/thin-provisioning-lvm2/

# https://medium.com/@mshajeer/pre-requisites-for-installing-glusterfs-with-ibm-cloud-private-a18c2b0ebafb
# https://kubesphere.com.cn/en/docs/reference/storage-system-installation/glusterfs-server/


