---
# Work in progress
    
# - name: Setup docker networks
#   hosts: swarm_managers[0]
#   tasks:
#     - name: Create docker network 'sbdi_frontend'
#       docker_network:
#         name: "sbdi_frontend"
#         scope: swarm
##         ipam_config:
##           - subnet: 10.211.1.0/24
            
- name: Install Docker Swarm Services
  hosts: swarm_managers[0]
  vars:
    docker_ctx: "{{ docker_root | default('/docker') }}"
    service_declarations: "{{ docker_services | dict2items }}"
  become: true
  tasks:
    - name: Deploy services
      include_role:
        name: "{{ service_declaration.value['role']}}"
      loop: "{{ service_declarations }}"
      loop_control:
        loop_var: service_declaration

    - name: Deploy HTTP proxy 
      include_role:
        name: 'httpproxy'

# - name: Setup ha proxy access
#   hosts: access-1
#   become: true
#   roles:
#     - haproxy

# TODO: Setup on all access nodes.
