---
- name: Setup SSH access to Servers (Phase I)
  hosts: localhost
  tasks:
    - name: Remove previous hostname realted SSH keys from known hosts
      shell: "ssh-keygen -R {{ deployment_prefix }}-{{ item }}"
      ignore_errors: yes
      with_items: "{{ groups['gateways']  + groups['servers'] }}"
    - name: Remove previous fqdn related SSH keys from known hosts
      shell: "ssh-keygen -R {{ deployment_prefix }}-{{ item }}.{{ domain }}"
      ignore_errors: yes
      with_items: "{{ groups['gateways']  + groups['servers'] }}"
    - name: Remove previous ip related SSH keys from known host
      shell: "ssh-keygen -R {{  hostvars[item]['floating_ip'] }}"
      ignore_errors: yes
      with_items: "{{ groups['gateways']  }}"
    - name: Accept SSH host keys for gatway hostnames
      shell:  "ssh-keyscan -H {{ deployment_prefix }}-{{ item }} >> ~/.ssh/known_hosts"
      with_items: "{{ groups['gateways'] }}"
    - name: Accept SSH host keys for gateway fqdn
      shell:  "ssh-keyscan -H {{ deployment_prefix }}-{{ item }}.{{ domain }} >> ~/.ssh/known_hosts"
      with_items: "{{ groups['gateways'] }}"
      
- name: Setup Name Resolution (i.e. generate /etc/hosts file) on Gateways
  hosts: gateways
  remote_user: ubuntu
  become: true
  roles:
  - role: roles/name_resolution/etc_hosts

- name: Setup SSH access to Servers (Phase II)
  hosts: localhost
  tasks:
  - name: Accept SSH host keys for server hostnames
    shell:  "ssh ubuntu@{{ deployment_prefix }}-{{ groups['gateways'][0] }} ssh-keyscan -H {{ deployment_prefix }}-{{ item }} >> ~/.ssh/known_hosts"
    with_items: "{{ groups['servers'] }}"
  - name: Accept SSH host keys for server fqdn
    shell:  "ssh ubuntu@{{ deployment_prefix }}-{{ groups['gateways'][0] }} ssh-keyscan -H {{ deployment_prefix }}-{{ item }}.{{ domain }} >> ~/.ssh/known_hosts"
    with_items: "{{ groups['servers'] }}"
      
- name: Setup Name Resolution (i.e. generate /etc/hosts file) on Servers
  hosts: servers
  remote_user: ubuntu
  become: true
  vars:
    ansible_ssh_common_args: "-J ubuntu@{{ deployment_prefix }}-{{ groups['gateways'][0] }}.{{ domain }}"
  roles:
    - role: roles/name_resolution/etc_hosts
#      tags: etchosts


#      register: known_hosts_script
#      changed_when: "'found' not in known_hosts_script.stdout"  
