--- 
- name: Install Docker Appplications
  hosts: swarm_managers[0]
  vars:
    docker_ctx: "{{  docker_root | default('/docker') }}"
  become: true
  roles:
    - osticket
  tasks:
    - name: Setup env for Osticket
      copy:
        src: docker/etc/osticket/env/{{ deployment_prefix }}/envosticket
        dest: "{{ docker_ctx }}/etc/osticket/env/.envosticket"
        decrypt: yes
        mode: 0640
        backup: no

  
