--- 
- name: Initialize servers and gatways 
  hosts: servers:gateways
  become: true
  tasks:
  - name: Add docker repo key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present    
  - name: Add docker repo
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
      state: present
  - name: Update and upgrade
    apt:
      upgrade: dist
      update_cache: yes
      cache_valid_time: 86400 #One day
      autoclean: yes
      autoremove: yes
      lock_timeout: 120
    register: apt_upgrade_status
  # - debug:
  #     var: apt_upgrade_status
  - name: Wait for upgrade to complete
    wait_for_connection:
      delay: 10
    when: apt_upgrade_status.changed
  - name: Check if reboot needed
    stat: 
      path: /var/run/reboot-required
    register: reboot_required_marker_file
  # - debug:
  #     var: reboot_required_marker_file
  - name: Reboot the machine
    reboot:
    when: reboot_required_marker_file.stat.exists
  - name: Wait for reboot to complete
    wait_for_connection:
      delay: 10
    when: reboot_required_marker_file.stat.exists
      
- name: Install basic sw, utility scripts, auotupdates and nrpe client
  hosts: servers:gateways
  become: true
  roles:
    - role: sbdi_utility_scripts
    - role: autoupdate
      tags:
        - autoupdate
        - nrpeclient
  tasks:
  - name: Install basic packages
    apt:
      pkg:
      - net-tools
      - ca-certificates
      - software-properties-common
      - docker-ce
      - emacs-nox
      - elpa-yaml-mode
  - name: Download and install docker compose
    get_url:
      url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
      timeout: 30
      dest: /usr/local/bin/docker-compose
      owner: root
      mode: 755

  