--- 
- name: Configure users on servers
  hosts: servers
  remote_user: ubuntu
  become: true
  vars:
    ansible_host: "{{deployment_prefix}}_{{  inventory_hostname }}.{{ domain }}"
    ansible_ssh_common_args: "-J ubuntu@{{ deployment_prefix }}_{{ groups['gateways'][0] }}.{{ domain }}"
  tasks:
  - name: Create user notroot
    user:
      name: notroot
      comment: "Notroot"
      uid: 1100
      group: admin
      groups: sudo
      append: yes
      shell: /bin/bash
      password: "{{ notroot_passwords[inventory_hostname] | password_hash('sha512', password_salt) }}"
      state: present
  - name: Create users 
    user:
      name: "{{ item.key }}"
      comment: "{{ item.value['full_name'] }}"
      uid: "{{ item.value['uuid'] }}"
      groups: sudo
      append: yes
      shell: /bin/bash
      password: "{{ item.value['password_hash'] }}"
      state: present
    with_dict: "{{ admin_users }}"
