---
- name: XYZ
  hosts: localhost
  tasks:
    - name: "Get volume info"
      openstack.cloud.volume_info:
      register: volume_info
      
    # - name: "Print volume info"
    #   debug:
    #     var:  item.name
    #   with_items: "{{ volume_info.volumes }}"
    #   when: item.name | regex_search("^(.*)-$")
    
- name: testing testing
  hosts: manager-1
  gather_facts: yes
  tasks:
    - name: "Filter out volume device id for host"
      set_fact:
        volume_device_id:  "virtio-{{item.id}}"
      with_items: "{{ hostvars['localhost'].volume_info.volumes }}"
      when: item.name | regex_search("^(.*)"+inventory_hostname+"-volume$")

    - name: Find lvm_device
      debug:
        var: volume_device_id
      

    - name: Find lvm_device
      debug:
        var: item.key
      with_items: "{{ ansible_facts.devices }}"
#      when: item.links.ids is defined

