---
# ansible-playbook upgrade_and_reboot.yml --extra-vars "selected_hosts=['<inventory hostname>']"
#
- name: Update, upgrade and reboot hosts when needed
  hosts: "{{ selected_hosts | default('servers:gateways') }}"
  serial: 1
  become: true
  tasks:
  - name: Update and upgrade
    apt:
      upgrade: dist
      update_cache: yes
      cache_valid_time: 86400 #One day
      autoclean: yes
      autoremove: yes
      lock_timeout: 120
    register: apt_upgrade_status
    tags:
      - upgrade

  - name: Wait for upgrade to complete
    wait_for_connection:
      delay: 10
    when: apt_upgrade_status.changed
    tags:
      - upgrade
    
  - name: Check if reboot needed
    stat: 
      path: /var/run/reboot-required
    register: reboot_required_marker_file
    tags:
      - reboot
      
  - name: Reboot the machine
    reboot:
      reboot_timeout: 3600
    when: reboot_required_marker_file.stat.exists
    tags:
      - reboot
      
  - name: Wait for reboot to complete
    wait_for_connection:
      delay: 10
    when: reboot_required_marker_file.stat.exists
    tags:
      - reboot
