version: '3.7'

networks:
  {{ frontend_network }}:
    external: true

configs:
  config_sds:
    file: "${DOCKER_CTX:-/docker}/etc/sds/config/sds-config.properties"
services:
  sds:
    image: bioatlas/ala-sds:v1.1
    environment:
      JAVA_OPTS: -Xmx1g -Xms128m -Xss256k -Djava.awt.headless=true -Dlog4j2.formatMsgNoLookups=true
    volumes:
      - data_nameindex:/data/lucene/namematching
    configs:
      - source: config_sds
        target: /data/sds/config/sds-config.properties
    networks:
      - {{ frontend_network }}

volumes:
  data_nameindex:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${DOCKER_CTX:-/docker}/var/volumes/nameindex/data_nameindex"
