---
# tasks file for authentication
- name: Ensure configuration and script directories
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - etc
    - etc/authentication
    - etc/authentication/env
    - etc/authentication/config
    - etc/authentication/apikey/initdb.d
    - etc/authentication/cas/initdb.d
    - usr/authentication
    - usr/authentication/bin
  tags:
    - app_directory

- name: Ensure write access for docker group
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    mode: 0775
    group: docker
    recurse: yes
    state: directory
  with_items:
    - etc/authentication
    - usr/authentication
  tags:
    - write_access

- name: Install "envapikey.template"
  copy:
    src: etc/envapikey.template
    dest: "{{ docker_ctx }}/etc/authentication/env/envapikey.template"
    mode: 0644
  tags:
    - env_template

- name: Install "envcas.template"
  copy:
    src: etc/envcas.template
    dest: "{{ docker_ctx }}/etc/authentication/env/envcas.template"
    mode: 0644
  tags:
    - env_template

- name: Copy apikey database initialization files
  copy:
    src : "{{ item }}"
    dest : "{{ docker_ctx | default('/docker') }}/etc/authentication/apikey/initdb.d"
    mode: 0644
  with_items:
    - etc/apikey/initdb.d/
  tags:
    - db_schema

- name: Copy CAS database initialization files
  copy:
    src : "{{ item }}"
    dest : "{{ docker_ctx | default('/docker') }}/etc/authentication/cas/initdb.d"
    mode: 0644
  with_items:
    - etc/cas/initdb.d/
  tags:
    - db_schema

- name: Install "mongo-init.sh"
  copy:
    src: etc/mongo-init.sh
    dest: "{{ docker_ctx | default('/docker') }}/etc/authentication/mongo-init.sh"
    mode: 0644
  tags:
    - db_schema

- name: Install "docker-compose.yml"
  template:
    src: etc/docker-compose.yml
    dest: "{{ docker_ctx | default('/docker') }}/etc/authentication/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  tags:
    - docker_compose

- name: Install apikey configuration files
  template:
    src: etc/config/apikey-config.yml
    dest: "{{ docker_ctx | default('/docker') }}/etc/authentication/config/apikey-config.yml"
    mode: 0644
  tags:
    - app_config

- name: Install userdetails configuration files
  template:
    src: etc/config/userdetails-config.yml
    dest: "{{ docker_ctx | default('/docker') }}/etc/authentication/config/userdetails-config.yml"
    mode: 0644
  tags:
    - app_config

- name: Install cas5 configuration files
  template:
    src: etc/config/cas5-config.yml
    dest: "{{ docker_ctx | default('/docker') }}/etc/authentication/config/cas5-config.yml"
    mode: 0644
  tags:
    - app_config

- name: Install pwe configuration files
  template:
    src: etc/config/pwe.properties
    dest: "{{ docker_ctx | default('/docker') }}/etc/authentication/config/pwe.properties"
    mode: 0644
  tags:
    - app_config

- name: Install cas-management configuration files
  template:
    src: etc/config/cas-management-config.properties
    dest: "{{ docker_ctx | default('/docker') }}/etc/authentication/config/cas-management-config.properties"
    mode: 0644
  tags:
    - app_config

- name: Install "application.cfg"
  template:
    src: etc/application.cfg
    dest: "{{ docker_ctx | default('/docker') }}/etc/authentication/application.cfg"
    mode: 0644
  tags:
    - application_cfg

- name: Install "proxy.conf"
  template:
    src: etc/proxy.conf
    dest: "{{ docker_ctx | default('/docker') }}/etc/authentication/proxy.conf"
    mode: 0644
  tags:
    - proxy_conf

- name: Install "wait-for-it.sh"
  template:
    src: etc/wait-for-it.sh
    dest: "{{ docker_ctx | default('/docker') }}/etc/authentication/wait-for-it.sh"
    mode: 0755
  tags:
    - wait_for_it
