---
# tasks file for sds
- name: Ensure configuration and script directories
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - etc
    - etc/sds
    - etc/sds/env
    - etc/sds/config
    - usr/sds
    - usr/sds/bin
  tags:
    - app_directory

- name: Ensure write access for docker group
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    mode: 0775
    group: docker
    recurse: yes
    state: directory
  with_items:
    - etc/sds
  tags:
    - write_access

- name: Install "envsds.template"
  copy:
    src: etc/envsds.template
    dest: "{{ docker_ctx }}/etc/sds/env/envsds.template"
    mode: 0644
  tags:
    - env_template

- name: Install "docker-compose.yml"
  template:
    src: etc/docker-compose.yml
    dest: "{{ docker_ctx | default('/docker') }}/etc/sds/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  tags:
    - docker_compose

- name: Install sds configuration file
  template:
    src: etc/config/sds-config.properties
    dest: "{{ docker_ctx | default('/docker') }}/etc/sds/config/sds-config.properties"
    mode: 0644
  tags:
    - app_config

- name: Install "application.cfg"
  template:
    src: etc/application.cfg
    dest: "{{ docker_ctx | default('/docker') }}/etc/sds/application.cfg"
    mode: 0644
  tags:
    - application_cfg

- name: Install "proxy.conf"
  template:
    src: etc/proxy.conf
    dest: "{{ docker_ctx | default('/docker') }}/etc/sds/proxy.conf"
    mode: 0644
  tags:
    - proxy_conf
