version: '3.7'

networks:
  {{ frontend_network }}:
    external: true

configs:
  config_logger:
    file: "${DOCKER_CTX:-/docker}/etc/loggerservice/config/logger-config.properties"

services:
  loggerservice:
    image: bioatlas/ala-loggerservice:v1.0
    environment:
      JAVA_OPTS: -Xmx1g -Xms128m -Xss256k -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom -Dlog4j2.formatMsgNoLookups=true
    env_file: "${DOCKER_CTX:-/docker}/etc/loggerservice/env/.envlogger"
    configs:
      - source: config_logger
        target: /tmp/logger-config.properties
    volumes:
      - type: bind
        source: "${DOCKER_CTX:-/docker}/etc/loggerservice/wait-for-it.sh"
        target: /wait-for-it.sh
    command: /bin/ash -c "envsubst < /tmp/logger-config.properties > /data/logger/config/logger-config.properties && /bin/bash /wait-for-it.sh mysqldblogger:3306 --timeout=60 --strict && catalina.sh run"
    networks:
      - {{ frontend_network }}

  mysqldblogger:
    image: mysql:5.7
    env_file: "${DOCKER_CTX:-/docker}/etc/loggerservice/env/.envlogger"
    volumes:
#      - type: bind
#        source: "${DOCKER_CTX:-/docker}/etc/loggerservice/initdb.d"
#        target: /docker-entrypoint-initdb.d
      - type: volume
        source: db_data_loggerservice
        target: /var/lib/mysql
    networks:
      - {{ frontend_network }}

volumes:
  db_data_loggerservice:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${DOCKER_CTX:-/docker}/var/volumes/loggerservice/db_data_loggerservice"
