- name: Unmount backup data device
  mount:
    path: /mnt
    src: "{{ backup_data_device }}"
    state: absent
- name: Read backup data device information (always use unit when probing)
  parted: "device={{ backup_data_device }} unit=MiB"
  register: data_device_info
- name: Output disks
  debug:
    msg: "{{ sdb_info }}"
- name: Remove all partitions from data device
  parted:
    device: "{{ backup_data_device }}"
    number: "{{ item.num }}"
    state: absent
  with_items:
   - "{{ data_device_info.partitions }}"

- name: Reboot the machine (workarround for bug in sticky mount)
  reboot:    

- name: Install ZFS
  apt:
    pkg: zfsutils-linux

- name: Create mount point /backup
  file:
    path: /backup
    state: directory
    owner: root
    group: root
    mode: 0775
    
- name: Create a zpool
  command: "zpool create -O compression=gzip -m /backup -f backup {{ backup_data_device }}"
 

