---
# tasks file for spatial
- name: Ensure configuration and script directories
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - etc
    - etc/spatial
    - etc/spatial/env
    - etc/spatial/config
    - etc/spatial/db
    - etc/spatial/db/initdb.d
    - usr/spatial
    - usr/spatial/bin
    - var/volumes
    - var/volumes/spatial
  tags:
    - app_directory

- name: Ensure write access for docker group
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    mode: 0775
    group: docker
    # recurse: yes
    state: directory
  with_items:
    - var/volumes/spatial
    - etc/spatial
  tags:
    - write_access

- name: Install "envgeoserver.template"
  copy:
    src: etc/envgeoserver.template
    dest: "{{ docker_ctx }}/etc/spatial/env/envgeoserver.template"
    mode: 0644
  tags:
    - env_template

- name: Install "envpostgis.template"
  copy:
    src: etc/envpostgis.template
    dest: "{{ docker_ctx }}/etc/spatial/env/envpostgis.template"
    mode: 0644
  tags:
    - env_template

- name: Install "envspatial.template"
  copy:
    src: etc/envspatial.template
    dest: "{{ docker_ctx }}/etc/spatial/env/envspatial.template"
    mode: 0644
  tags:
    - env_template

- name: Install "layersdb.sql"
  copy:
    src: etc/layersdb.sql
    dest: "{{ docker_ctx }}/etc/spatial/db/initdb.d/layersdb.sql"
    mode: 0644
  tags:
    - db_schema

- name: Install "pg_hba.conf"
  copy:
    src: etc/pg_hba.conf
    dest: "{{ docker_ctx | default('/docker') }}/etc/spatial/config/pg_hba.conf"
    mode: 0644
  tags:
    - db_conf

- name: Install "docker-compose.yml"
  template:
    src: etc/docker-compose.yml
    dest: "{{ docker_ctx | default('/docker') }}/etc/spatial/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  tags:
    - docker_compose

- name: Install spatialhub configuration files
  template:
    src: etc/config/spatial-hub-config.yml
    dest: "{{ docker_ctx | default('/docker') }}/etc/spatial/config/spatial-hub-config.yml"
    mode: 0644
  tags:
    - app_config

- name: Install spatialhub menu configuration files
  template:
    src: etc/config/menu-config.json
    dest: "{{ docker_ctx | default('/docker') }}/etc/spatial/config/menu-config.json"
    mode: 0644
  tags:
    - app_config

- name: Install spatialhub view configuration files
  template:
    src: etc/config/view-config.json
    dest: "{{ docker_ctx | default('/docker') }}/etc/spatial/config/view-config.json"
    mode: 0644
  tags:
    - app_config

- name: Install spatial-service configuration files
  template:
    src: etc/config/spatial-service-config.yml
    dest: "{{ docker_ctx | default('/docker') }}/etc/spatial/config/spatial-service-config.yml"
    mode: 0644
  tags:
    - app_config

- name: Install "application.cfg"
  template:
    src: etc/application.cfg
    dest: "{{ docker_ctx | default('/docker') }}/etc/spatial/application.cfg"
    mode: 0644
  tags:
    - application_cfg

- name: Install "proxy.conf"
  template:
    src: etc/proxy.conf
    dest: "{{ docker_ctx | default('/docker') }}/etc/spatial/proxy.conf"
    mode: 0644
  tags:
    - proxy_conf

- name: Install "wait-for-it.sh"
  template:
    src: etc/wait-for-it.sh
    dest: "{{ docker_ctx | default('/docker') }}/etc/spatial/wait-for-it.sh"
    mode: 0755
  tags:
    - wait_for_it
